apiVersion: apps/v1
kind: Deployment
metadata:
  name: camera-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app  # Updated to match labels in the pod template
  template:
    metadata:
      labels:
        name: camera-deployment
        app: my-app
    spec:
      containers:
        - name: app-image
          image: bilallaaroussi/stoopid:v20
         # ports:
         #   - containerPort: 3002

#camera does not need a service
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: camera-service
#spec:
#  type: NodePort
#  ports:
#    - port: 80
#      targetPort: 3000  # Updated to match containerPort in the Deployment
#      nodePort: 30006
#  selector:
#    app: my-app  # Updated to match labels in the Deployment 
