apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: database-pod
      app: my-app 
  template:
    metadata:
      labels:
        name: database-pod
        app: my-app
    spec:
      containers:
        - name: database-image
          image: bilallaaroussi/database-image:5
          ports:
            - containerPort: 3035
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  selector:
    name: database-pod
    app: my-app
  ports:
    - protocol: TCP
      port: 3035
      targetPort: 3035
